In [64]:
import numpy as np
print(np.__version__)

1.25.2


In [65]:
import numpy as np
a=np.array([1,2,3,4])

In [66]:
a

array([1, 2, 3, 4])

In [67]:
print(a)

[1 2 3 4]


In [68]:
a.ndim

1

In [69]:
a.shape

(4,)

In [70]:
import numpy as np
a=np.array([[1,2,3,4],[8,9,7,5]])

In [71]:
a

array([[1, 2, 3, 4],
       [8, 9, 7, 5]])

In [72]:
print(a)

[[1 2 3 4]
 [8 9 7 5]]


In [73]:
a.ndim

2

In [74]:
a.shape

(2, 4)

In [75]:
import numpy as np
a=np.array([[1,2,3,9],[5,45,65,55],[6,36,18,94],[7,14,21,85],[8,16,24,64]])

In [76]:
a.ndim

2

In [77]:
a.shape

(5, 4)

In [78]:
import numpy as np
b=np.array([[[1,5]],[[2,9]],[[3,63],]])

In [79]:
b.shape

(3, 1, 2)

In [80]:
import numpy as np
c=np.array([[[3,4,6,8,9]],[[3,4,6,8,9]],[[3,4,6,8,9]]])

In [81]:
c.shape

(3, 1, 5)

In [82]:
import numpy as np
z=np.ones([3,4])
print (z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [83]:
import numpy as np
z=np.arange(3,20)
print (z)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [84]:
import numpy as np
z=np.linspace(1,2,num=13)
print (z)

[1.         1.08333333 1.16666667 1.25       1.33333333 1.41666667
 1.5        1.58333333 1.66666667 1.75       1.83333333 1.91666667
 2.        ]


In [85]:
import numpy as np
z=np.linspace(1,2,num=13,endpoint=False)
print (z)

[1.         1.07692308 1.15384615 1.23076923 1.30769231 1.38461538
 1.46153846 1.53846154 1.61538462 1.69230769 1.76923077 1.84615385
 1.92307692]


In [86]:
import numpy as np
r=np.array(np.arange(1,36))
print (r)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35]


In [87]:
r.ndim

1

In [88]:
print(np.where(r<14))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64),)


In [89]:
print(r[:,2:6])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
import numpy as np
r=np.array(np.arange(0,36)).reshape(3,4,3)
r
r[::2,1::2,1::2]

array([[[ 4],
        [10]],

       [[28],
        [34]]])

In [ ]:
import numpy as np
a=np.array(np.arange(1,6))
l=[1,2,3]
print(a[l])

[2 3 4]


In [ ]:
#for row add use axis=1,for column use axis=0
import numpy as np
a=np.array([[17,26,38],[46,55,60]])
average=np.mean(a)
average=round(average,ndigits=2)
print(average)

40.33


In [ ]:
import numpy as np
a=np.array([[17,26,38],[46,55,60],[95,86,79]])
print(np.mean(a))

55.77777777777778


In [ ]:
# flaten in column major by order f,row major by order c, for memory location by k it make copy
import numpy as np
a=np.arange(1,37).reshape(4,9)
c=a.flatten(order='F')
print(c)

[ 1 10 19 28  2 11 20 29  3 12 21 30  4 13 22 31  5 14 23 32  6 15 24 33
  7 16 25 34  8 17 26 35  9 18 27 36]


In [ ]:
# ravel in column major by order f,row major by order c, for memory location by k it does not make copy
import numpy as np
a=np.arange(1,37).reshape(4,9)
c=a.ravel(order='F')
print(c)

[ 1 10 19 28  2 11 20 29  3 12 21 30  4 13 22 31  5 14 23 32  6 15 24 33
  7 16 25 34  8 17 26 35  9 18 27 36]


In [ ]:
import numpy as np
a=np.arange(1,28).reshape(3,3,3)
b=np.arange(11,38).reshape(3,3,3)
print(a)
print()
print(b)
print("after concat")
c=np.hstack((a,b))
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

[[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[29 30 31]
  [32 33 34]
  [35 36 37]]]
after concat
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [11 12 13]
  [14 15 16]
  [17 18 19]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]
  [20 21 22]
  [23 24 25]
  [26 27 28]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]
  [29 30 31]
  [32 33 34]
  [35 36 37]]]


In [ ]:
import numpy as np
a=np.arange(1,28)
s=np.split(a,9)
print(s)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12]), array([13, 14, 15]), array([16, 17, 18]), array([19, 20, 21]), array([22, 23, 24]), array([25, 26, 27])]
