In [1]:
import numpy as np
print(np.__version__)

1.25.2


In [4]:
import numpy as np
a=np.array([1,2,3,4])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
print(a)

[1 2 3 4]


In [7]:
a.ndim

1

In [8]:
a.shape

(4,)

In [16]:
import numpy as np
a=np.array([[1,2,3,4],[8,9,7,5]])

In [17]:
a

array([[1, 2, 3, 4],
       [8, 9, 7, 5]])

In [18]:
print(a)

[[1 2 3 4]
 [8 9 7 5]]


In [13]:
a.ndim

2

In [19]:
a.shape

(2, 4)

In [4]:
import numpy as np
a=np.array([[1,2,3,9],[5,45,65,55],[6,36,18,94],[7,14,21,85],[8,16,24,64]])

In [21]:
a.ndim

2

In [5]:
a.shape

(5, 4)

In [35]:
import numpy as np
b=np.array([[[1,5]],[[2,9]],[[3,63],]])

In [36]:
b.shape

(3, 1, 2)

In [41]:
import numpy as np
c=np.array([[[3,4,6,8,9]],[[3,4,6,8,9]],[[3,4,6,8,9]]])

In [42]:
c.shape

(3, 1, 5)

In [4]:
import numpy as np
z=np.ones([3,4])
print (z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
import numpy as np
z=np.arange(3,20)
print (z)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
import numpy as np
z=np.linspace(1,2,num=13)
print (z)

[1.         1.08333333 1.16666667 1.25       1.33333333 1.41666667
 1.5        1.58333333 1.66666667 1.75       1.83333333 1.91666667
 2.        ]


In [8]:
import numpy as np
z=np.linspace(1,2,num=13,endpoint=False)
print (z)

[1.         1.07692308 1.15384615 1.23076923 1.30769231 1.38461538
 1.46153846 1.53846154 1.61538462 1.69230769 1.76923077 1.84615385
 1.92307692]


In [10]:
import numpy as np
r=np.array([np.arange(10,25),np.arange(30,45)])
print (r)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]]


In [19]:
print(r[0,3])

13


In [20]:
print(r[:,2:6])

[[12 13 14 15]
 [32 33 34 35]]


In [68]:
import numpy as np
r=np.array(np.arange(0,36)).reshape(3,4,3)
r
r[::2,1::2,1::2]

array([[[ 4],
        [10]],

       [[28],
        [34]]])